# Generated by Django 4.2.6 on 2023-12-08 19:53

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="nickname",
            ),
        ),
    ]
