# Generated by Django 4.2.6 on 2023-11-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0005_remove_book_user"),
        ("reviewapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookapp.book"
            ),
        ),
    ]
