# Generated by Django 4.2.6 on 2023-12-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviewapp", "0003_rename_user_review_writer_alter_review_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
