# Generated by Django 4.2.6 on 2023-11-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelfapp", "0002_alter_bookshelf_book_alter_bookshelf_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookshelf",
            unique_together=set(),
        ),
    ]
