# Generated by Django 4.2.6 on 2023-11-09 05:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0002_remove_book_booknumber_alter_book_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookshelfapp", "0003_alter_bookshelf_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookshelf",
            unique_together={("user", "book")},
        ),
    ]
