# Generated by Django 4.2.6 on 2023-11-10 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookapp", "0003_book_like_users"),
        ("bookshelfapp", "0004_alter_bookshelf_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookapp.book"
            ),
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
