# Generated by Django 4.2.6 on 2023-11-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelfapp", "0005_alter_bookshelf_book_alter_bookshelf_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookshelf",
            name="review",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookshelf",
            name="transcription",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
