# Generated by Django 4.2.6 on 2023-11-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0005_remove_book_user"),
        ("bookshelfapp", "0006_bookshelf_review_bookshelf_transcription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookapp.book",
            ),
        ),
    ]
