# Generated by Django 4.2.6 on 2023-11-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelfapp", "0008_alter_bookshelf_book"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookshelf",
            unique_together=set(),
        ),
    ]
