# Generated by Django 4.2.6 on 2023-11-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0005_remove_book_user"),
        ("bookshelfapp", "0009_alter_bookshelf_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookshelf",
                to="bookapp.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="review",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="transcription",
            field=models.TextField(null=True),
        ),
    ]
