# Generated by Django 4.2.6 on 2023-11-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelfapp", "0013_alter_bookshelf_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookshelf",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="bookshelf",
            name="review",
        ),
        migrations.RemoveField(
            model_name="bookshelf",
            name="transcription",
        ),
    ]
