# Generated by Django 4.2.6 on 2023-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("writer", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="book/")),
                (
                    "keyword",
                    models.CharField(
                        choices=[
                            ("novel", "소설"),
                            ("human", "인문"),
                            ("self", "자기계발"),
                            ("science", "과학"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
