# Generated by Django 4.2.6 on 2023-11-10 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookapp", "0002_remove_book_booknumber_alter_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="like_users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
