# Generated by Django 4.2.6 on 2023-11-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0003_book_like_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="like_users",
            new_name="user",
        ),
    ]
