# Generated by Django 4.2.6 on 2023-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0005_remove_book_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="keyword",
            field=models.CharField(
                choices=[
                    ("novel", "소설"),
                    ("human", "인문"),
                    ("self", "자기계발"),
                    ("science", "괴학"),
                ],
                max_length=10,
            ),
        ),
    ]
